apiVersion: v2
appVersion: 1.6.0
description: cert-manager webhook solver for DNSPod
name: cert-manager-webhook-dnspod
version: 1.6.0
type: application
maintainers:
- name: imroc
  email: roc@imroc.cc
